blueprint:
  name: Consumable Low/Depleted Notification
  description: >-
    Create a notification when a consumable reaches its warning threshold,
    and update it when the consumable is fully depleted. The notification
    is dismissed when the consumable is replaced. Supports persistent
    notifications (default), mobile app notifications, notification groups,
    and Android/Fire TV.
  domain: automation
  input:
    consumable_sensor:
      name: Consumable Sensor
      description: The consumable tracker sensor to monitor.
      selector:
        entity:
          filter:
            - domain: sensor
              integration: consumable_tracker
    warning_days_override:
      name: Warning Days Override
      description: >-
        Override the warning threshold (in days). Leave at 0 to use the
        sensor's configured warning_days attribute.
      default: 0
      selector:
        number:
          min: 0
          max: 365
          unit_of_measurement: days
    notify_device:
      name: Mobile Device (Optional)
      description: >-
        Select a device running the official Home Assistant app to receive
        notifications. Leave empty to use persistent notifications in the
        Home Assistant UI.
      default: false
      selector:
        device:
          filter:
            - integration: mobile_app
    notify_group:
      name: Notification Group or Android/Fire TV (Optional)
      description: >-
        The name of the notification group or TV to send notifications to
        (e.g., "notify.all_phones" or "living_room_tv"). If set, this
        overrides the Mobile Device selection above.
      default: ""
      selector:
        text:

mode: restart

triggers:
  - trigger: state
    entity_id: !input consumable_sensor
  - trigger: time
    at: "00:01:00"

variables:
  consumable_sensor: !input consumable_sensor
  warning_days_override: !input warning_days_override
  notify_device: !input notify_device
  notify_group: !input notify_group
  notify_group_target: >-
    {{ notify_group | lower | regex_replace('^notify\\.', '') | replace(' ', '_') }}
  use_notify_group: "{{ notify_group_target | length > 0 }}"
  use_notify_device: "{{ not use_notify_group and notify_device is defined and notify_device != false }}"
  use_persistent: "{{ not use_notify_group and not use_notify_device }}"
  device_name: "{{ device_attr(consumable_sensor, 'name') }}"
  consumable_name: "{{ state_attr(consumable_sensor, 'consumable_name') }}"
  display_name: "{{ device_name }} {{ consumable_name }}"
  days_remaining: "{{ states(consumable_sensor) | int(0) }}"
  warning_days: "{{ warning_days_override if warning_days_override > 0 else state_attr(consumable_sensor, 'warning_days') | int(0) }}"
  notification_id: "consumable_{{ consumable_sensor | replace('.', '_') }}"
  is_warning: "{{ days_remaining <= warning_days and days_remaining > 0 }}"
  is_depleted: "{{ days_remaining == 0 }}"
  is_normal: "{{ days_remaining > warning_days }}"
  device_link: "[{{ device_name }}](/config/devices/device/{{ device_id(consumable_sensor) }})"
  device_url: "/config/devices/device/{{ device_id(consumable_sensor) }}"

actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_depleted }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ use_notify_group }}"
                sequence:
                  - action: "notify.{{ notify_group_target }}"
                    data:
                      title: "{{ display_name }} Needs Replacement"
                      message: "{{ device_name }} {{ consumable_name }} is due for replacement."
                      data:
                        tag: "{{ notification_id }}"
                        clickAction: "{{ device_url }}"
              - conditions:
                  - condition: template
                    value_template: "{{ use_notify_device }}"
                sequence:
                  - device_id: !input notify_device
                    domain: mobile_app
                    type: notify
                    title: "{{ display_name }} Needs Replacement"
                    message: "{{ device_name }} {{ consumable_name }} is due for replacement."
                    data:
                      tag: "{{ notification_id }}"
                      clickAction: "{{ device_url }}"
            default:
              - action: persistent_notification.create
                data:
                  title: "{{ display_name }} Needs Replacement"
                  message: "{{ device_link }} {{ consumable_name }} is due for replacement."
                  notification_id: "{{ notification_id }}"
      - conditions:
          - condition: template
            value_template: "{{ is_warning }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ use_notify_group }}"
                sequence:
                  - action: "notify.{{ notify_group_target }}"
                    data:
                      title: "{{ display_name }} Replacement Soon"
                      message: "{{ device_name }} {{ consumable_name }} has {{ days_remaining }} days remaining."
                      data:
                        tag: "{{ notification_id }}"
                        clickAction: "{{ device_url }}"
              - conditions:
                  - condition: template
                    value_template: "{{ use_notify_device }}"
                sequence:
                  - device_id: !input notify_device
                    domain: mobile_app
                    type: notify
                    title: "{{ display_name }} Replacement Soon"
                    message: "{{ device_name }} {{ consumable_name }} has {{ days_remaining }} days remaining."
                    data:
                      tag: "{{ notification_id }}"
                      clickAction: "{{ device_url }}"
            default:
              - action: persistent_notification.create
                data:
                  title: "{{ display_name }} Replacement Soon"
                  message: "{{ device_link }} {{ consumable_name }} has {{ days_remaining }} days remaining."
                  notification_id: "{{ notification_id }}"
      - conditions:
          - condition: template
            value_template: "{{ is_normal }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ use_notify_group }}"
                sequence:
                  - action: "notify.{{ notify_group_target }}"
                    data:
                      message: "clear_notification"
                      data:
                        tag: "{{ notification_id }}"
              - conditions:
                  - condition: template
                    value_template: "{{ use_notify_device }}"
                sequence:
                  - device_id: !input notify_device
                    domain: mobile_app
                    type: notify
                    message: "clear_notification"
                    data:
                      tag: "{{ notification_id }}"
            default:
              - action: persistent_notification.dismiss
                data:
                  notification_id: "{{ notification_id }}"
