blueprint:
  name: Consumable Low/Depleted Notification
  description: >-
    Create a notification when a consumable reaches its warning threshold,
    and update it when the consumable is fully depleted. The notification
    is dismissed when the consumable is replaced. Supports persistent
    notifications and/or mobile app notifications.
  domain: automation
  input:
    consumable_sensor:
      name: Consumable Sensor
      description: The consumable tracker sensor to monitor.
      selector:
        entity:
          filter:
            - domain: sensor
              integration: consumable_tracker
    warning_days_override:
      name: Warning Days Override
      description: >-
        Override the warning threshold (in days). Leave at 0 to use the
        sensor's configured warning_days attribute.
      default: 0
      selector:
        number:
          min: 0
          max: 365
          unit_of_measurement: days
    persistent_notification:
      name: Persistent Notification
      description: >-
        Show a persistent notification in the Home Assistant UI.
      default: true
      selector:
        boolean:
    notify_devices:
      name: Mobile Devices (Optional)
      description: >-
        Select devices running the official Home Assistant app to receive
        notifications.
      default: []
      selector:
        device:
          multiple: true
          filter:
            - integration: mobile_app

mode: restart

triggers:
  - trigger: state
    entity_id: !input consumable_sensor
  - trigger: time
    at: "00:01:00"

variables:
  consumable_sensor: !input consumable_sensor
  warning_days_override: !input warning_days_override
  persistent_notification: !input persistent_notification
  notify_devices: !input notify_devices
  use_mobile: "{{ notify_devices | length > 0 }}"
  device_name: "{{ device_attr(consumable_sensor, 'name') }}"
  consumable_name: "{{ state_attr(consumable_sensor, 'consumable_name') }}"
  display_name: "{{ device_name }} {{ consumable_name }}"
  days_remaining: "{{ states(consumable_sensor) | int(0) }}"
  warning_days: "{{ warning_days_override if warning_days_override > 0 else state_attr(consumable_sensor, 'warning_days') | int(0) }}"
  notification_id: "consumable_{{ consumable_sensor | replace('.', '_') }}"
  is_warning: "{{ days_remaining <= warning_days and days_remaining > 0 }}"
  is_depleted: "{{ days_remaining == 0 }}"
  is_normal: "{{ days_remaining > warning_days }}"
  device_link: "[{{ device_name }}](/config/devices/device/{{ device_id(consumable_sensor) }})"
  device_url: "/config/devices/device/{{ device_id(consumable_sensor) }}"

actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_depleted }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ persistent_notification }}"
            then:
              - action: persistent_notification.create
                data:
                  title: "{{ display_name }} Needs Replacement"
                  message: "{{ device_link }} {{ consumable_name }} is due for replacement."
                  notification_id: "{{ notification_id }}"
          - if:
              - condition: template
                value_template: "{{ use_mobile }}"
            then:
              - repeat:
                  for_each: "{{ notify_devices }}"
                  sequence:
                    - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify(separator='_') }}"
                      data:
                        title: "{{ display_name }} Needs Replacement"
                        message: "{{ device_name }} {{ consumable_name }} is due for replacement."
                        data:
                          tag: "{{ notification_id }}"
                          clickAction: "{{ device_url }}"
      - conditions:
          - condition: template
            value_template: "{{ is_warning }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ persistent_notification }}"
            then:
              - action: persistent_notification.create
                data:
                  title: "{{ display_name }} Replacement Soon"
                  message: "{{ device_link }} {{ consumable_name }} has {{ days_remaining }} days remaining."
                  notification_id: "{{ notification_id }}"
          - if:
              - condition: template
                value_template: "{{ use_mobile }}"
            then:
              - repeat:
                  for_each: "{{ notify_devices }}"
                  sequence:
                    - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify(separator='_') }}"
                      data:
                        title: "{{ display_name }} Replacement Soon"
                        message: "{{ device_name }} {{ consumable_name }} has {{ days_remaining }} days remaining."
                        data:
                          tag: "{{ notification_id }}"
                          clickAction: "{{ device_url }}"
      - conditions:
          - condition: template
            value_template: "{{ is_normal }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ persistent_notification }}"
            then:
              - action: persistent_notification.dismiss
                data:
                  notification_id: "{{ notification_id }}"
          - if:
              - condition: template
                value_template: "{{ use_mobile }}"
            then:
              - repeat:
                  for_each: "{{ notify_devices }}"
                  sequence:
                    - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify(separator='_') }}"
                      data:
                        message: "clear_notification"
                        data:
                          tag: "{{ notification_id }}"
